name: myaml
description: Yaml file reader (mb writer)
author: meok
version: 1.0.0
homepage: https://github.com/meoook/dart-tools/yaml

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.16.8
